# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.11.1
_src_path: https://github.com/mbercx/python-copier
description: AiiDA plugin for thermo_pw software
doc_deploy: github
docs: myst
package_name: aiida-thermo_pw
